/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElM: typeof import('element-plus/es')['ElM']
  const ElMe: typeof import('element-plus/es')['ElMe']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElNotification: typeof import('element-plus/es')['ElNotification']
  const ElStep: typeof import('element-plus/es')['ElStep']
}
